hawkular_server:
  url: http://127.0.0.1:8080
  tenant: hawkular
  credentials:
    username: jdoe
    password: password
emitter:
  address: :8081
  status_enabled: true
  status_credentials:
    username: dev
    password: changeme
collector:
  minimum_collection_interval: 10s
  tags:
    agent-host: ${HOSTNAME}
kubernetes:
  master_url: https://10.193.22.70:8443
  ca_cert_file: /var/lib/origin/openshift.local.config/master/ca.crt
  token: UfD0hnaebU0G7Y3MXVVhCM5IrZzK6s_OsXJkLaSu_dw
  pod_name: hawkular-metrics-qhp8w
  pod_namespace: openshift-infra
endpoints:
  # the agent endpoint
  - type: prometheus
    enabled: false
    url: http://127.0.0.1:8081/metrics
    collection_interval: 10s
    tags:
      endpoint-name: hawkular-openshift-agent
  # prometheus-python-example
  - type: prometheus
    enabled: false
    url: http://127.0.0.1:8181/metrics
    collection_interval: 10s
    tags:
      endpoint-name: prometheus-python-example
  # go-expvar-example
  - type: json
    enabled: false
    url: http://127.0.0.1:8181/debug/vars
    collection_interval: 10s
    tags:
      endpoint-name: go-expvar-example
